# Generated by Django 5.1.3 on 2025-02-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buddymatchinguser",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
