# Generated by Django 5.1.3 on 2024-12-12 13:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyMatchingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('International Student', 'International Student'), ('Buddy', 'Buddy')], default='International Student', max_length=25)),
                ('surname', models.CharField(default='Mustermann', max_length=255)),
                ('first_name', models.CharField(default='Max', max_length=255)),
                ('preferred_language', models.CharField(choices=[('German', 'German'), ('English', 'English'), ('Both', 'Both')], default='English', max_length=10)),
                ('email', models.EmailField(default='default@stud.tu-darmstadt.de', max_length=255)),
                ('degree_level', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters')], default='Bachelors', max_length=10)),
                ('app_matr_number', models.PositiveIntegerField(blank=True, default=0, unique=True)),
                ('department', models.CharField(choices=[('FB 1', 'Rechts- und Wirtschaftswissenschaften (FB 1)'), ('FB 2', 'Gesellschafts- & Geschichtswissenschaften (FB 2)'), ('FB 3', 'Humanwissenschaften (FB 3)'), ('FB 4', 'Mathematik (FB 4)'), ('FB 5', 'Physik (FB 5)'), ('FB 7', 'Chemie (FB 7)'), ('FB 10', 'Biologie (FB 10)'), ('FB 11', 'Material- und Geowissenschaften (FB 11)'), ('FB 13', 'Bau- und Umweltingenieurwissenschaften (FB 13)'), ('FB 15', 'Architektur (FB 15)'), ('FB 16', 'Maschinenbau (FB 16)'), ('FB 18', 'Elektrotechnik und Informationstechnik (FB 18)'), ('FB 20', 'Informatik (FB 20)')], default='FB 1', max_length=50)),
                ('country', models.CharField(blank=True, default='none', max_length=255)),
                ('preferred_number_of_partners', models.PositiveIntegerField(default=1, null=True)),
                ('is_permitted', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('partners', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
