# Generated by Django 5.1.3 on 2024-12-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddymatchinguser',
            name='email',
            field=models.EmailField(default='default@stud.tu-darmstadt.de', max_length=255, unique=True),
        ),
    ]
