# Generated by Django 5.1.3 on 2024-11-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='text',
        ),
        migrations.AddField(
            model_name='entry',
            name='application_number',
            field=models.PositiveIntegerField(blank=True, default=0, unique=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='degree_level',
            field=models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters')], default='Bachelors', max_length=10),
        ),
        migrations.AddField(
            model_name='entry',
            name='department',
            field=models.CharField(choices=[('FB 1', 'Rechts- und Wirtschaftswissenschaften (FB 1)'), ('FB 2', 'Gesellschafts- & Geschichtswissenschaften (FB 2)'), ('FB 3', 'Humanwissenschaften (FB 3)'), ('FB 4', 'Mathematik (FB 4)'), ('FB 5', 'Physik (FB 5)'), ('FB 7', 'Chemie (FB 7)'), ('FB 10', 'Biologie (FB 10)'), ('FB 11', 'Material- und Geowissenschaften (FB 11)'), ('FB 13', 'Bau- und Umweltingenieurwissenschaften (FB 13)'), ('FB 15', 'Architektur (FB 15)'), ('FB 16', 'Maschinenbau (FB 16)'), ('FB 18', 'Elektrotechnik und Informationstechnik (FB 18)'), ('FB 20', 'Informatik (FB 20)')], default='FB 1', max_length=50),
        ),
        migrations.AddField(
            model_name='entry',
            name='e_mail',
            field=models.EmailField(default='default@stud.tu-darmstadt.de', max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='first_name',
            field=models.CharField(default='Max', max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='matriculation_number',
            field=models.PositiveIntegerField(blank=True, default=0, unique=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='partners',
            field=models.ManyToManyField(blank=True, default=None, to='helloapp.entry'),
        ),
        migrations.AddField(
            model_name='entry',
            name='prefered_number_of_partners',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='preferred_country',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='preferred_language',
            field=models.CharField(choices=[('German', 'German'), ('English', 'English'), ('Both', 'Both')], default='English', max_length=10),
        ),
        migrations.AddField(
            model_name='entry',
            name='role',
            field=models.CharField(choices=[('International Student', 'International Student'), ('Buddy', 'Buddy')], default='International Student', max_length=25),
        ),
        migrations.AddField(
            model_name='entry',
            name='sending_country',
            field=models.CharField(blank=True, default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='surname',
            field=models.CharField(default='Mustermann', max_length=255),
        ),
    ]
