# Generated by Django 5.1.3 on 2024-12-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0002_alter_buddymatchinguser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddymatchinguser',
            name='username',
        ),
    ]
