# Generated by Django 5.1.3 on 2024-11-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0002_remove_entry_text_entry_application_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='e_mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='prefered_number_of_partners',
            new_name='preferred_number_of_partners',
        ),
        migrations.AlterField(
            model_name='entry',
            name='partners',
            field=models.ManyToManyField(blank=True, to='helloapp.entry'),
        ),
    ]
