# Generated by Django 5.1.3 on 2025-01-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0002_alter_buddymatchinguser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddymatchinguser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
