# Generated by Django 5.1.3 on 2024-12-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0003_remove_buddymatchinguser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddymatchinguser',
            name='role',
            field=models.CharField(choices=[('International Student', 'International Student'), ('Buddy', 'Buddy')], default='Buddy', max_length=25),
        ),
    ]
