# Generated by Django 5.1.3 on 2024-11-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0003_rename_e_mail_entry_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='application_number',
            new_name='app_matr_number',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='sending_country',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='matriculation_number',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='preferred_country',
        ),
    ]
