# Generated by Django 5.1.3 on 2024-11-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0004_rename_application_number_entry_app_matr_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_permitted',
            field=models.BooleanField(default=False),
        ),
    ]
