# Generated by Django 5.1.3 on 2024-12-29 09:31

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0004_alter_buddymatchinguser_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='buddymatchinguser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='buddymatchinguser',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Sports', 'Sports'), ('Culture', 'Culture'), ('Nature', 'Nature'), ('Technology', 'Technology')], max_length=32),
        ),
        migrations.AlterField(
            model_name='buddymatchinguser',
            name='is_permitted',
            field=models.BooleanField(default=True),
        ),
    ]
