# Generated by Django 5.1.3 on 2025-01-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0005_alter_buddymatchinguser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='Willkommen auf der Seite!')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
