# Generated by Django 5.1.3 on 2025-01-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0006_homepagetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddymatchinguser',
            name='country',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='buddymatchinguser',
            name='department',
            field=models.CharField(choices=[('FB 1', 'Law and Economics (FB 1)'), ('FB 2', 'Social and Historical Sciences (FB 2)'), ('FB 3', 'Human Sciences (FB 3)'), ('FB 4', 'Mathematics (FB 4)'), ('FB 5', 'Physics (FB 5)'), ('FB 7', 'Chemistry (FB 7)'), ('FB 10', 'Biology (FB 10)'), ('FB 11', 'Material and Earth Sciences (FB 11)'), ('FB 13', 'Civil and Environmental Engineering (FB 13)'), ('FB 15', 'Architecture (FB 15)'), ('FB 16', 'Mechanical Engineering (FB 16)'), ('FB 18', 'Electrical Engineering and IT (FB 18)'), ('FB 20', 'Computer Science (FB 20)')], default='FB 1', max_length=50),
        ),
    ]
