# Generated by Django 5.1.3 on 2025-01-18 15:18

import helloapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0007_alter_buddymatchinguser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddymatchinguser',
            name='deletion_date',
            field=models.DateField(default=helloapp.models.default_deletion_date, help_text='Das Datum, an dem der Account gelöscht wird.'),
        ),
        migrations.AddField(
            model_name='buddymatchinguser',
            name='last_reset',
            field=models.DateField(default=helloapp.models.default_last_reset, help_text='Das letzte Mal, als der Countdown zurückgesetzt wurde.'),
        ),
    ]
