# Generated by Django 5.1.3 on 2025-01-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0008_buddymatchinguser_deletion_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagetext',
            name='content',
        ),
        migrations.AddField(
            model_name='homepagetext',
            name='content_de',
            field=models.TextField(default='Willkommen auf der Seite!', verbose_name='Content in German'),
        ),
        migrations.AddField(
            model_name='homepagetext',
            name='content_en',
            field=models.TextField(default='Welcome to the page!', verbose_name='Content in English'),
        ),
    ]
