# Generated by Django 5.1.3 on 2025-02-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_feedback', models.TextField(blank=True, help_text='Provide your detailed feedback.')),
                ('rating_1', models.CharField(choices=[('EX', 'Excellent'), ('VG', 'Very Good'), ('G', 'Good'), ('F', 'Fair'), ('P', 'Poor'), ('NA', 'N/A')], help_text='Rate your experience.', max_length=2)),
                ('rating_2', models.CharField(choices=[('EX', 'Excellent'), ('VG', 'Very Good'), ('G', 'Good'), ('F', 'Fair'), ('P', 'Poor'), ('NA', 'N/A')], help_text='Rate the matching process.', max_length=2)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
