# Generated by Django 5.1.3 on 2025-03-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(default='Email Not Found', help_text='Email of the student who submitted the feedback.', max_length=254)),
                ('q1', models.CharField(choices=[('Student', 'Student'), ('Buddy', 'Buddy')], max_length=7, null=True)),
                ('q2', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('q3', models.PositiveBigIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('q4', models.CharField(choices=[('Admission letter', 'Admission letter'), ('International Relations Unit website', 'International Relations Unit website'), ('International Student Services website', 'International Student Services website'), ('Orientation Programmes', 'Orientation Programmes'), ('Social-media channels', 'Social-media channels'), ('Friends and fellow students', 'Friends and fellow students')], max_length=100, null=True)),
                ('q5', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('I did not need any support', 'I did not need any support')], max_length=100, null=True)),
                ('q5_details', models.TextField(blank=True)),
                ('q6', models.CharField(choices=[('Late', 'Late'), ('Easy', 'Easy'), ('Difficult', 'Difficult'), ('I was never contacted', 'I was never contacted')], max_length=100, null=True)),
                ('q7', models.CharField(choices=[('Regular', 'Regular'), ('Low', 'Low'), ('Inexistent', 'Inexistent')], max_length=100, null=True)),
                ('q8', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Sometimes', 'Sometimes')], max_length=100, null=True)),
                ('q8_details', models.TextField(blank=True)),
                ('q9', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=100, null=True)),
                ('q9_details', models.TextField(blank=True)),
                ('q10', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['submitted_at'], name='feedback_fe_submitt_c84e00_idx')],
            },
        ),
    ]
