# Generated by Django 5.1.3 on 2025-03-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='q8',
            field=models.CharField(choices=[('Yes/Sometimes', 'Yes/Sometimes'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q9',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No/Maybe', 'No/Maybe')], max_length=100, null=True),
        ),
    ]
