# Generated by Django 5.1.3 on 2025-02-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="rating_1",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="rating_2",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="text_feedback",
        ),
        migrations.AddField(
            model_name="feedback",
            name="q1",
            field=models.CharField(
                choices=[("Student", "Student"), ("Buddy", "Buddy")],
                max_length=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="q10",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="q2",
            field=models.PositiveIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], null=True
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="q3",
            field=models.PositiveBigIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], null=True
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="q4",
            field=models.CharField(
                choices=[
                    ("Admission letter", "Admission letter"),
                    (
                        "International Relations Unit website",
                        "International Relations Unit website",
                    ),
                    (
                        "International Student Services website",
                        "International Student Services website",
                    ),
                    ("Orientation Programmes", "Orientation Programmes"),
                    ("Social-media channels", "Social-media channels"),
                    ("Friends and fellow students", "Friends and fellow students"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="q5",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("I did not need any support", "I did not need any support"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="q5_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="q6",
            field=models.CharField(
                choices=[
                    ("Late", "Late"),
                    ("Easy", "Easy"),
                    ("Difficult", "Difficult"),
                    ("I was never contacted", "I was never contacted"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="q7",
            field=models.CharField(
                choices=[
                    ("Regular", "Regular"),
                    ("Low", "Low"),
                    ("Inexistent", "Inexistent"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="q8",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Sometimes", "Sometimes")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="q8_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="q9",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Maybe", "Maybe")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="q9_details",
            field=models.TextField(blank=True),
        ),
    ]
