# Generated by Django 5.1.3 on 2025-03-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='student',
        ),
        migrations.AddField(
            model_name='feedback',
            name='student_email',
            field=models.EmailField(default='Email Not Found', help_text='Email of the student who submitted the feedback.', max_length=254),
        ),
    ]
