# Generated by Django 5.1.3 on 2025-03-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0003_remove_feedback_student_feedback_student_email"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["submitted_at"], name="feedback_fe_submitt_c84e00_idx"
            ),
        ),
    ]
