name: Auto-format

on:
  issue_comment:
    types: [created]

jobs:
  format:
    permissions:
      pull-requests: read
      contents: write
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/format' }}
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        id: branch_name
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            return pullRequest.head.ref;

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch_name.outputs.result }}

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          npm install --global prettier

      - name: Run formatters (Prettier, Djlint, Ruff)
        run: |
          # Format JavaScript, TypeScript, and CSS
          npx prettier --write "myproject/static/**/*.js" "myproject/static/**/*.ts" "myproject/static/**/*.css"
          
          # Format Python & Django templates
          ruff format .
          djlint . --reformat

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet || echo "changes=true" >> $GITHUB_ENV

      - name: Commit changes
        if: env.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Apply automatic formatting and fix typos"
          git push